
const $ = (id) => document.getElementById(id);
const feetInput = $('feet');
const inchesInput = $('inches');
const decimalsSelect = $('decimals');
const resultOutput = $('result');
const calculateBtn = $('calculateBtn');
const resetBtn = $('resetBtn');
const calculatorCard = document.querySelector('.calculator-card');
const calculatorKey = calculatorCard ? (calculatorCard.dataset.calculator || '') : '';
const pathParts = window.location.pathname.split('/').filter(Boolean);
const lastPart = pathParts[pathParts.length - 1] || '';
const currentPage = lastPart ? (lastPart.includes('.html') ? lastPart : lastPart + '.html') : 'index.html';
function n(id){const el=$(id); if(!el) return NaN; return parseFloat(el.value);} function d(){return decimalsSelect?parseInt(decimalsSelect.value,10):2;} function money(v){return '$'+Number(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});} function pct(v){return Number(v).toFixed(d())+'%';} function out(s){if(resultOutput) resultOutput.textContent=s;} function monthsToText(m){if(!isFinite(m)||m<0) return 'Not payable with these inputs'; if(m===0) return '0 months'; const y=Math.floor(m/12), mo=Math.ceil(m%12); return ((y?y+' years ':'')+(mo?mo+' months':'')) || '0 months';}
const calculatorConfigs={
'feet-to-metres.html':()=>{const dec=d(), f=n('feet'), i=parseFloat((inchesInput&&inchesInput.value)||'0'); if(isNaN(f)&&isNaN(i)) return out('Please enter feet and/or inches'); const sf=isNaN(f)?0:f, si=isNaN(i)?0:i; const total=sf+(si/12); out(sf+"'"+si+'" = '+(total*0.3048).toFixed(dec)+' m');},
'metres-to-feet.html':()=>{const dec=d(), m=n('feet'); if(isNaN(m)) return out('Please enter a valid number'); const total=m*3.28084; let f=Math.floor(total), inch=(total-f)*12; inch=dec===0?Math.round(inch):parseFloat(inch.toFixed(dec)); if(inch>=12){f+=1;inch=0;} out(m+' m = '+f+"'"+inch+'"');},
'cm-to-inches.html':()=>{const v=n('feet'); if(isNaN(v)) return out('Please enter a valid number'); out(v+' cm = '+(v/2.54).toFixed(d())+' inches');},
'inches-to-cm.html':()=>{const v=n('feet'); if(isNaN(v)) return out('Please enter a valid number'); out(v+' inches = '+(v*2.54).toFixed(d())+' cm');},

'mortgage-calculator.html':()=>{const loan=n('loan'), rate=n('rate')/100/12, years=n('years'); if(isNaN(loan)||isNaN(rate)||isNaN(years)||loan<=0||years<=0)return out('Enter loan amount, rate, and term.'); const months=years*12; const payment=rate===0?loan/months:loan*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1); out('Estimated monthly payment: '+money(payment)+' • Total interest: '+money(payment*months-loan));},
'loan-payment.html':()=>{const loan=n('loan'), rate=n('rate')/100/12, years=n('years'); if(isNaN(loan)||isNaN(rate)||isNaN(years)||loan<=0||years<=0)return out('Enter loan amount, rate, and term.'); const months=years*12; const payment=rate===0?loan/months:loan*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1); out('Monthly payment: '+money(payment)+' • Total repayment: '+money(payment*months)+' • Interest: '+money(payment*months-loan));},
'auto-loan.html':()=>{const price=n('price'), deposit=n('deposit')||0, rate=n('rate')/100/12, years=n('years'); const loan=price-deposit; if(isNaN(price)||isNaN(rate)||isNaN(years)||loan<=0||years<=0)return out('Enter vehicle price, deposit, rate, and term.'); const months=years*12; const payment=rate===0?loan/months:loan*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1); out('Amount financed: '+money(loan)+' • Monthly payment: '+money(payment)+' • Interest: '+money(payment*months-loan));},
'rent-vs-buy.html':()=>{const rent=n('rent'), home=n('homepayment'), owner=n('ownerextra')||0, renter=n('renterextra')||0; if(isNaN(rent)||isNaN(home))return out('Enter rent and mortgage payment.'); const rentTotal=rent+renter, buyTotal=home+owner, diff=buyTotal-rentTotal; out('Rent estimate: '+money(rentTotal)+'/mo • Buy estimate: '+money(buyTotal)+'/mo • '+(diff>0?'Buying costs '+money(diff)+' more per month':'Buying costs '+money(Math.abs(diff))+' less per month'));},
'credit-card-payoff.html':()=>{let bal=n('balance'), rate=n('rate')/100/12, pay=n('payment'); if([bal,rate,pay].some(isNaN)||pay<=bal*rate) return out('Enter a payment greater than monthly interest.'); let m=0, interest=0; while(bal>0&&m<1200){let int=bal*rate; interest+=int; bal=bal+int-pay; m++;} out('Estimated payoff: '+monthsToText(m)+' • Estimated interest: '+money(interest));},
'debt-payoff.html':()=>calculatorConfigs['credit-card-payoff.html'](),
'debt-to-income.html':()=>{const debt=n('debt'), income=n('income'); if(isNaN(debt)||isNaN(income)||income<=0)return out('Enter valid debt and income.'); out('Debt-to-income ratio: '+pct(debt/income*100));},
'net-worth.html':()=>{const a=n('assets'), l=n('liabilities'); if(isNaN(a)||isNaN(l))return out('Enter assets and liabilities.'); out('Estimated net worth: '+money(a-l));},
'refinance-savings.html':()=>{const c=n('current'), ne=n('new'), costs=n('costs')||0; if(isNaN(c)||isNaN(ne))return out('Enter current and new payments.'); const save=c-ne; out('Monthly savings: '+money(save)+' • Break-even: '+(save>0?monthsToText(costs/save):'No monthly saving'));},
'down-payment.html':()=>{const p=n('price'), entry=n('percent'); if(isNaN(p)||isNaN(entry)||p<=0||entry<0)return out('Enter a valid purchase price and down payment.'); const isAmount=entry>100; const dp=isAmount?entry:p*entry/100; if(dp>p)return out('Down payment cannot be greater than the purchase price.'); const per=dp/p*100; out('Down payment: '+money(dp)+' ('+per.toFixed(d())+'%) • Remaining loan: '+money(p-dp));},
'emergency-fund.html':()=>{const e=n('expenses'), m=n('months'); if(isNaN(e)||isNaN(m))return out('Enter expenses and months.'); out('Emergency fund target: '+money(e*m));},
'savings-goal.html':()=>{const t=n('target'), c=n('current')||0, m=n('months'); if(isNaN(t)||isNaN(m)||m<=0)return out('Enter target and months.'); const remaining=t-c; if(remaining<=0)return out('Goal already reached.'); out('Monthly saving needed: '+money(remaining/m));},
'compound-interest.html':()=>{let p=n('principal')||0, c=n('contribution')||0, r=n('rate')/100/12, years=n('years'); if(isNaN(r)||isNaN(years))return out('Enter rate and years.'); let v=p; for(let i=0;i<years*12;i++){v=v*(1+r)+c;} out('Estimated future value: '+money(v));},
'simple-interest.html':()=>{const p=n('principal'), r=n('rate')/100, y=n('years'); if([p,r,y].some(isNaN))return out('Enter all values.'); out('Simple interest: '+money(p*r*y)+' • Total: '+money(p+(p*r*y)));},
'hourly-to-salary.html':()=>{const r=n('rate'), h=n('hours'); if(isNaN(r)||isNaN(h))return out('Enter rate and hours.'); const w=r*h; out('Weekly: '+money(w)+' • Annual: '+money(w*52));},
'pay-raise.html':()=>{const c=n('current'), r=n('raise'); if(isNaN(c)||isNaN(r))return out('Enter current pay and raise.'); out('New pay: '+money(c*(1+r/100))+' • Increase: '+money(c*r/100));},
'overtime.html':()=>{const r=n('rate'), reg=n('regular')||0, ot=n('overtime')||0, mult=n('multiplier')||1.5; if(isNaN(r))return out('Enter hourly rate.'); out('Estimated pay: '+money((r*reg)+(r*mult*ot)));},
'paycheck.html':()=>{const g=n('gross'), de=n('deductions')||0; if(isNaN(g))return out('Enter gross pay.'); out('Estimated take-home pay: '+money(g*(1-de/100)));},
'sales-tax.html':()=>{const p=n('price'), t=n('tax'); if(isNaN(p)||isNaN(t))return out('Enter price and tax rate.'); out('Tax: '+money(p*t/100)+' • Total: '+money(p*(1+t/100)));},
'credit-utilization.html':()=>{const b=n('balance'), l=n('limit'); if(isNaN(b)||isNaN(l)||l<=0)return out('Enter balance and limit.'); out('Credit utilization: '+pct(b/l*100));},
'credit-utilization-calculator.html':()=>calculatorConfigs['credit-utilization.html'](),
'current-ratio.html':()=>{const a=n('assets'), l=n('liabilities'); if(isNaN(a)||isNaN(l)||l<=0)return out('Enter assets and liabilities.'); out('Current ratio: '+(a/l).toFixed(d())+':1');},
'quick-ratio.html':()=>{const c=n('cash')||0, r=n('receivables')||0, l=n('liabilities'); if(isNaN(l)||l<=0)return out('Enter liabilities.'); out('Quick ratio: '+((c+r)/l).toFixed(d())+':1');},
'contribution-margin.html':()=>{const p=n('price'), v=n('variable'); if(isNaN(p)||isNaN(v)||p<=0)return out('Enter price and variable cost.'); const cm=p-v; out('Contribution margin: '+money(cm)+' • Margin: '+pct(cm/p*100));},
'depreciation.html':()=>{const c=n('cost'), s=n('salvage')||0, l=n('life'); if(isNaN(c)||isNaN(l)||l<=0)return out('Enter cost and useful life.'); out('Annual depreciation: '+money((c-s)/l));},
'percentage-increase.html':()=>{const o=n('old'), ne=n('new'); if(isNaN(o)||isNaN(ne)||o===0)return out('Enter valid values.'); out('Percentage increase: '+pct((ne-o)/o*100));},
'percentage-decrease.html':()=>{const o=n('old'), ne=n('new'); if(isNaN(o)||isNaN(ne)||o===0)return out('Enter valid values.'); out('Percentage decrease: '+pct((o-ne)/o*100));},
'discount.html':()=>{const p=n('price'), dis=n('discount'); if(isNaN(p)||isNaN(dis))return out('Enter price and discount.'); out('Sale price: '+money(p*(1-dis/100))+' • You save: '+money(p*dis/100));},
'bmi.html':()=>{const w=n('weight'), h=n('height')/100; if(isNaN(w)||isNaN(h)||h<=0)return out('Enter weight and height.'); out('BMI: '+(w/(h*h)).toFixed(d()));},
'bmi-calculator.html':()=>calculatorConfigs['bmi.html'](),
'age.html':()=>{const v=$('date1').value; if(!v)return out('Choose a date.'); const b=new Date(v), now=new Date(); if(b>now)return out('Date of birth cannot be in the future.'); let age=now.getFullYear()-b.getFullYear(); const m=now.getMonth()-b.getMonth(); if(m<0||(m===0&&now.getDate()<b.getDate())) age--; out('Age: '+age+' years');},
'date-difference.html':()=>{const v1=$('date1').value, v2=$('date2').value; if(!v1||!v2)return out('Choose both dates.'); const a=new Date(v1), b=new Date(v2); if(isNaN(a)||isNaN(b))return out('Choose both dates.'); out('Difference: '+Math.abs(Math.round((b-a)/86400000))+' days');},
'paint.html':()=>{const a=n('area'), cov=n('coverage'), coats=n('coats')||1; if(isNaN(a)||isNaN(cov)||cov<=0)return out('Enter area and coverage.'); out('Paint needed: '+(a*coats/cov).toFixed(d())+' litres');},
'flooring.html':()=>{const a=n('area'), w=n('waste')||10; if(isNaN(a))return out('Enter floor area.'); out('Flooring needed: '+(a*(1+w/100)).toFixed(d())+' m²');},

'mortgage-amortization.html':()=>{const loan=n('loan'), rate=n('rate')/100/12, years=n('years'); if(isNaN(loan)||isNaN(rate)||isNaN(years)||loan<=0||years<=0)return out('Enter loan amount, rate, and term.'); const months=years*12; const payment=rate===0?loan/months:loan*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1); out('Monthly payment: '+money(payment)+' • Total repayment: '+money(payment*months)+' • Total interest: '+money(payment*months-loan));}
,'extra-payment-mortgage.html':()=>{const loan=n('loan'), rate=n('rate')/100/12, years=n('years'), extra=n('extra')||0; if(isNaN(loan)||isNaN(rate)||isNaN(years)||loan<=0||years<=0)return out('Enter loan amount, rate, term, and optional extra payment.'); const months=years*12; const base=rate===0?loan/months:loan*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1); let bal=loan,m=0,int=0,pay=base+extra; while(bal>0&&m<months){let i=bal*rate; int+=i; bal=bal+i-pay; m++;} const baseInt=base*months-loan; out('New payoff: '+monthsToText(m)+' • Interest saved: '+money(Math.max(0,baseInt-int)));}
,'offset-account-savings.html':()=>{const loan=n('loan'), offset=n('offset')||0, rate=n('rate')/100, years=n('years'); if(isNaN(loan)||isNaN(rate)||isNaN(years)||loan<=0||years<=0)return out('Enter loan amount, offset balance, rate, and years.'); const effective=Math.max(0,Math.min(offset,loan)); out('Estimated simple interest saved: '+money(effective*rate*years));}
,'debt-snowball.html':()=>{let bal=n('balance'), rate=n('rate')/100/12, pay=n('payment'); if([bal,rate,pay].some(isNaN)||bal<=0||pay<=bal*rate)return out('Enter a payment greater than monthly interest.'); let m=0,int=0; while(bal>0&&m<1200){let i=bal*rate; int+=i; bal=bal+i-pay; m++;} out('Estimated payoff: '+monthsToText(m)+' • Interest: '+money(int));}
,'debt-avalanche.html':()=>calculatorConfigs['debt-snowball.html']()
,'investment-return.html':()=>{let p=n('principal')||0,c=n('contribution')||0,r=n('rate')/100/12,years=n('years'); if(isNaN(r)||isNaN(years)||years<=0)return out('Enter rate and years.'); let v=p; for(let i=0;i<years*12;i++){v=v*(1+r)+c;} out('Estimated future value: '+money(v)+' • Contributions: '+money(p+c*years*12));}
,'retirement-savings.html':()=>calculatorConfigs['investment-return.html']()
,'fire.html':()=>{const e=n('expenses'), swr=n('rate'), cur=n('current')||0; if(isNaN(e)||isNaN(swr)||e<=0||swr<=0)return out('Enter annual expenses and withdrawal rate.'); const target=e/(swr/100); out('Estimated FIRE target: '+money(target)+' • Remaining: '+money(Math.max(0,target-cur)));}
,
'weighted-average.html':()=>{const vals=($('values').value||'').split(',').map(Number), ws=($('weights').value||'').split(',').map(Number); if(vals.length!==ws.length||vals.some(isNaN)||ws.some(isNaN))return out('Enter matching comma-separated values and weights.'); const sw=ws.reduce((a,b)=>a+b,0); if(sw===0)return out('Weights must add up to more than zero.'); const s=vals.reduce((a,v,i)=>a+v*ws[i],0); out('Weighted average: '+(s/sw).toFixed(4));}
};

/* Stabilisation configs for newer calculator pages that use the shared feet/inches/decimals IDs. */
function textVal(id){const el=$(id); return el ? String(el.value || '').trim() : '';}
function numberList(id){const raw=textVal(id); return raw.split(/[,\s]+/).map(Number).filter(v=>!isNaN(v));}
function dt(id){const v=textVal(id); return v ? new Date(v) : null;}
function daysBetween(a,b){return Math.round((b-a)/86400000);}
function formatNumber(v){return Number(v).toFixed(d());}
function simplePayoff(balance, annualRate, payment){const r=annualRate/100/12; if([balance,annualRate,payment].some(isNaN)||balance<=0||payment<=balance*r)return null; let bal=balance,m=0,int=0; while(bal>0&&m<1200){let i=bal*r; int+=i; bal=bal+i-payment; m++;} return {months:m,interest:int};}
function loanPayment(loan, annualRate, years){const r=annualRate/100/12, months=years*12; return r===0?loan/months:loan*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1);}
Object.assign(calculatorConfigs,{
'age-calculator.html':()=>{const birth=dt('feet'), asof=dt('inches')||new Date(); if(!birth||isNaN(birth))return out('Choose a date of birth.'); if(birth>asof)return out('Date of birth cannot be after the calculation date.'); let age=asof.getFullYear()-birth.getFullYear(); const m=asof.getMonth()-birth.getMonth(); if(m<0||(m===0&&asof.getDate()<birth.getDate()))age--; out('Age: '+age+' years');},
'age-difference-calculator.html':()=>{const a=dt('feet'), b=dt('inches'); if(!a||!b||isNaN(a)||isNaN(b))return out('Choose both dates.'); out('Age difference: '+Math.abs(daysBetween(a,b))+' days');},
'average-calculator.html':()=>{const v=numberList('feet'); if(!v.length)return out('Enter numbers separated by commas.'); out('Average: '+formatNumber(v.reduce((a,b)=>a+b,0)/v.length));},
'body-surface-area-calculator.html':()=>{const w=n('feet'), h=n('inches'); if(isNaN(w)||isNaN(h)||w<=0||h<=0)return out('Enter weight and height.'); out('Estimated body surface area: '+Math.sqrt((h*w)/3600).toFixed(2)+' m²');},
'break-even-calculator.html':()=>{const fixed=n('feet'), price=n('inches'), variable=d(); if(isNaN(fixed)||isNaN(price)||isNaN(variable)||price<=variable)return out('Enter fixed cost, price, and a variable cost below price.'); out('Break-even units: '+Math.ceil(fixed/(price-variable)).toLocaleString());},
'business-days-calculator.html':()=>{const a=dt('feet'), b=dt('inches'); if(!a||!b||isNaN(a)||isNaN(b))return out('Choose both dates.'); let start=new Date(Math.min(a,b)), end=new Date(Math.max(a,b)), count=0; for(let x=new Date(start);x<=end;x.setDate(x.getDate()+1)){const day=x.getDay(); if(day!==0&&day!==6)count++;} out('Business days: '+count);},
'business-profit-planner-calculator.html':()=>{const units=n('feet'), profit=n('inches'); if(isNaN(units)||isNaN(profit))return out('Enter units and profit per unit.'); out('Estimated profit: '+money(units*profit));},
'celsius-to-fahrenheit.html':()=>{const v=n('feet'); if(isNaN(v))return out('Please enter a valid number'); out(v+' °C = '+((v*9/5)+32).toFixed(d())+' °F');},
'fahrenheit-to-celsius.html':()=>{const v=n('feet'); if(isNaN(v))return out('Please enter a valid number'); out(v+' °F = '+((v-32)*5/9).toFixed(d())+' °C');},
'commission-calculator.html':()=>{const sales=n('feet'), rate=n('inches'), base=d(); if(isNaN(sales)||isNaN(rate))return out('Enter sales and commission rate.'); out('Commission: '+money(sales*rate/100)+' • Total pay: '+money((sales*rate/100)+(isNaN(base)?0:base)));},
'compound-interest-calculator.html':()=>{const p=n('feet'), r=n('inches')/100/12, years=d(); if(isNaN(p)||isNaN(r)||isNaN(years))return out('Enter principal, rate, and years.'); const months=years*12; out('Estimated future value: '+money(p*Math.pow(1+r,months)));},
'concrete-calculator.html':()=>{const l=n('feet'), w=n('inches'), depth=d(); if(isNaN(l)||isNaN(w)||isNaN(depth))return out('Enter length, width, and depth.'); out('Concrete volume: '+(l*w*depth).toFixed(2)+' m³');},
'contribution-margin-calculator.html':()=>{const p=n('feet'), v=n('inches'); if(isNaN(p)||isNaN(v)||p<=0)return out('Enter selling price and variable cost.'); const cm=p-v; out('Contribution margin: '+money(cm)+' • Margin: '+(cm/p*100).toFixed(2)+'%');},
'countdown-calculator.html':()=>{const target=dt('feet'); if(!target||isNaN(target))return out('Choose a future date.'); const days=Math.ceil((target-new Date())/86400000); out(days>=0?'Countdown: '+days+' days':'That date has passed.');},
'credit-card-payoff-calculator.html':()=>{const r=simplePayoff(n('feet'),n('inches'),d()); if(!r)return out('Enter a payment greater than monthly interest.'); out('Estimated payoff: '+monthsToText(r.months)+' • Estimated interest: '+money(r.interest));},
'cups-to-ml-calculator.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter cups.'); out(v+' cups = '+(v*236.588).toFixed(2)+' mL');},
'current-ratio-calculator.html':()=>{const a=n('feet'), l=n('inches'); if(isNaN(a)||isNaN(l)||l<=0)return out('Enter assets and liabilities.'); out('Current ratio: '+(a/l).toFixed(2)+':1');},
'date-add-calculator.html':()=>{const a=dt('feet'), days=n('inches'); if(!a||isNaN(a)||isNaN(days))return out('Choose a start date and days to add.'); a.setDate(a.getDate()+days); out('Result date: '+a.toLocaleDateString());},
'days-between-dates-calculator.html':()=>{const a=dt('feet'), b=dt('inches'); if(!a||!b||isNaN(a)||isNaN(b))return out('Choose both dates.'); out('Difference: '+Math.abs(daysBetween(a,b))+' days');},
'debt-avalanche-calculator.html':()=>calculatorConfigs['credit-card-payoff-calculator.html'](),
'debt-payoff-calculator.html':()=>calculatorConfigs['credit-card-payoff-calculator.html'](),
'debt-snowball-calculator.html':()=>calculatorConfigs['credit-card-payoff-calculator.html'](),
'debt-to-income-calculator.html':()=>{const debt=n('feet'), income=n('inches'); if(isNaN(debt)||isNaN(income)||income<=0)return out('Enter debt and income.'); out('Debt-to-income ratio: '+(debt/income*100).toFixed(2)+'%');},
'depreciation-calculator.html':()=>{const cost=n('feet'), salvage=n('inches'), life=d(); if(isNaN(cost)||isNaN(life)||life<=0)return out('Enter cost and useful life.'); out('Annual depreciation: '+money((cost-(isNaN(salvage)?0:salvage))/life));},
'discount-calculator.html':()=>{const price=n('feet'), disc=n('inches'); if(isNaN(price)||isNaN(disc))return out('Enter price and discount.'); out('Sale price: '+money(price*(1-disc/100))+' • You save: '+money(price*disc/100));},
'down-payment-calculator.html':()=>{const price=n('feet'), pct=n('inches'); if(isNaN(price)||isNaN(pct))return out('Enter price and down payment percentage.'); const dp=price*pct/100; out('Down payment: '+money(dp)+' • Remaining loan: '+money(price-dp));},
'due-date-calculator.html':()=>{const lmp=dt('feet'); if(!lmp||isNaN(lmp))return out('Choose the first day of the last period.'); lmp.setDate(lmp.getDate()+280); out('Estimated due date: '+lmp.toLocaleDateString());},
'emergency-fund-calculator.html':()=>{const e=n('feet'), m=n('inches'); if(isNaN(e)||isNaN(m))return out('Enter expenses and months.'); out('Emergency fund target: '+money(e*m));},
'extra-payment-mortgage-calculator.html':()=>{const loan=n('feet'), rate=n('inches'), extra=d(); if(isNaN(loan)||isNaN(rate))return out('Enter loan amount and rate.'); const years=30, base=loanPayment(loan,rate,years); let bal=loan,m=0,int=0,pay=base+(isNaN(extra)?0:extra); while(bal>0&&m<years*12){let i=bal*rate/100/12; int+=i; bal=bal+i-pay; m++;} out('New payoff: '+monthsToText(m)+' • Monthly payment used: '+money(pay));},
'fire-calculator.html':()=>{const expenses=n('feet'), swr=n('inches'), current=d(); if(isNaN(expenses)||isNaN(swr)||swr<=0)return out('Enter expenses and withdrawal rate.'); const target=expenses/(swr/100); out('Estimated FIRE target: '+money(target)+' • Remaining: '+money(Math.max(0,target-(isNaN(current)?0:current))));},
'flooring-calculator.html':()=>{const l=n('feet'), w=n('inches'), waste=d(); if(isNaN(l)||isNaN(w))return out('Enter room length and width.'); out('Flooring needed: '+(l*w*(1+(isNaN(waste)?10:waste)/100)).toFixed(2)+' m²');},
'gallons-to-litres-calculator.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter gallons.'); out(v+' US gal = '+(v*3.78541).toFixed(2)+' L');},
'gpa-calculator.html':()=>{const grades=numberList('feet'), credits=numberList('inches'); if(!grades.length)return out('Enter grades.'); if(credits.length===grades.length){const sw=credits.reduce((a,b)=>a+b,0); return out('GPA: '+(grades.reduce((a,g,i)=>a+g*credits[i],0)/sw).toFixed(d()));} out('GPA: '+(grades.reduce((a,b)=>a+b,0)/grades.length).toFixed(d()));},
'gravel-calculator.html':()=>{const area=n('feet'), depth=n('inches'); if(isNaN(area)||isNaN(depth))return out('Enter area and depth.'); out('Gravel volume: '+(area*(depth/100)).toFixed(2)+' m³');},
'hourly-to-salary-calculator.html':()=>{const rate=n('feet'), hours=n('inches'); if(isNaN(rate)||isNaN(hours))return out('Enter rate and hours.'); const weekly=rate*hours; out('Weekly: '+money(weekly)+' • Annual: '+money(weekly*52));},
'hours-between-dates-calculator.html':()=>{const a=dt('feet'), b=dt('inches'); if(!a||!b||isNaN(a)||isNaN(b))return out('Choose both dates and times.'); out('Difference: '+(Math.abs(b-a)/3600000).toFixed(2)+' hours');},
'ideal-weight-calculator.html':()=>{const h=n('feet'), adj=n('inches')||0; if(isNaN(h)||h<=0)return out('Enter height.'); const base=22*Math.pow(h/100,2); out('Estimated ideal weight: '+(base*(1+adj/100)).toFixed(1)+' kg');},
'inflation-calculator.html':()=>{const price=n('feet'), rate=n('inches'), years=d(); if(isNaN(price)||isNaN(rate)||isNaN(years))return out('Enter price, inflation rate, and years.'); out('Future price: '+money(price*Math.pow(1+rate/100,years)));},
'investment-return-calculator.html':()=>{const p=n('feet'), rate=n('inches'), years=d(); if(isNaN(p)||isNaN(rate)||isNaN(years))return out('Enter starting amount, return, and years.'); out('Estimated future value: '+money(p*Math.pow(1+rate/100,years)));},
'kg-to-lb.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter kilograms.'); out(v+' kg = '+(v*2.20462).toFixed(d())+' lb');},
'lb-to-kg.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter pounds.'); out(v+' lb = '+(v/2.20462).toFixed(d())+' kg');},
'km-to-miles.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter kilometres.'); out(v+' km = '+(v*0.621371).toFixed(d())+' miles');},
'miles-to-km.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter miles.'); out(v+' miles = '+(v*1.60934).toFixed(d())+' km');},
'kph-to-mph-calculator.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter speed.'); out(v+' km/h = '+(v*0.621371).toFixed(2)+' mph');},
'mph-to-kph-calculator.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter speed.'); out(v+' mph = '+(v*1.60934).toFixed(2)+' km/h');},
'mulch-calculator.html':()=>{const area=n('feet'), depth=n('inches'); if(isNaN(area)||isNaN(depth))return out('Enter area and mulch depth.'); out('Mulch volume: '+(area*(depth/100)).toFixed(2)+' m³');},
'lean-body-mass-calculator.html':()=>{const w=n('feet'), h=n('inches'); if(isNaN(w)||isNaN(h))return out('Enter weight and height.'); out('Estimated lean body mass: '+((0.407*w)+(0.267*h)-19.2).toFixed(1)+' kg');},
'litres-per-square-metre-calculator.html':()=>{const litres=n('feet'), area=n('inches'); if(isNaN(litres)||isNaN(area)||area<=0)return out('Enter litres and area.'); out('Litres per square metre: '+(litres/area).toFixed(2)+' L/m²');},
'litres-to-gallons-calculator.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter litres.'); out(v+' L = '+(v/3.78541).toFixed(2)+' US gal');},
'loan-repayment-calculator.html':()=>{const loan=n('feet'), rate=n('inches'), years=d(); if(isNaN(loan)||isNaN(rate)||isNaN(years)||years<=0)return out('Enter loan amount, rate, and years.'); const payment=loanPayment(loan,rate,years); out('Monthly payment: '+money(payment)+' • Total interest: '+money(payment*years*12-loan));},
'margin-calculator.html':()=>{const revenue=n('feet'), cost=n('inches'); if(isNaN(revenue)||isNaN(cost)||revenue<=0)return out('Enter revenue and cost.'); out('Profit: '+money(revenue-cost)+' • Margin: '+((revenue-cost)/revenue*100).toFixed(2)+'%');},
'markup-calculator.html':()=>{const cost=n('feet'), markup=n('inches'); if(isNaN(cost)||isNaN(markup))return out('Enter cost and markup.'); out('Selling price: '+money(cost*(1+markup/100)));},
'median-calculator.html':()=>{const v=numberList('feet').sort((a,b)=>a-b); if(!v.length)return out('Enter numbers separated by commas.'); const mid=Math.floor(v.length/2), med=v.length%2?v[mid]:(v[mid-1]+v[mid])/2; out('Median: '+med);},
'ml-to-cups-calculator.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter mL.'); out(v+' mL = '+(v/236.588).toFixed(2)+' cups');},
'mode-calculator.html':()=>{const v=numberList('feet'); if(!v.length)return out('Enter numbers separated by commas.'); const c={}; v.forEach(x=>c[x]=(c[x]||0)+1); const max=Math.max(...Object.values(c)); out('Mode: '+Object.keys(c).filter(k=>c[k]===max).join(', '));},
'mortgage-amortization-calculator.html':()=>calculatorConfigs['loan-repayment-calculator.html'](),
'net-worth-calculator.html':()=>{const a=n('feet'), l=n('inches'); if(isNaN(a)||isNaN(l))return out('Enter assets and liabilities.'); out('Estimated net worth: '+money(a-l));},
'offset-account-calculator.html':()=>{const offset=n('feet'), rate=n('inches'), years=d(); if(isNaN(offset)||isNaN(rate)||isNaN(years))return out('Enter offset balance, rate, and years.'); out('Estimated simple interest saved: '+money(offset*rate/100*years));},
'one-rep-max-calculator.html':()=>{const weight=n('feet'), reps=n('inches'); if(isNaN(weight)||isNaN(reps))return out('Enter weight and reps.'); out('Estimated one-rep max: '+(weight*(1+reps/30)).toFixed(1));},
'overtime-calculator.html':()=>{const rate=n('feet'), hours=n('inches'), mult=d(); if(isNaN(rate)||isNaN(hours))return out('Enter rate and hours.'); const regular=Math.min(hours,40), overtime=Math.max(0,hours-40); out('Estimated pay: '+money(regular*rate+overtime*rate*(isNaN(mult)?1.5:mult)));},
'ovulation-calculator.html':()=>{const start=dt('feet'), cycle=n('inches')||28; if(!start||isNaN(start))return out('Choose the first day of the last period.'); const ov=new Date(start); ov.setDate(ov.getDate()+cycle-14); out('Estimated ovulation date: '+ov.toLocaleDateString());},
'pace-calculator.html':()=>{const dist=n('feet'), mins=n('inches'); if(isNaN(dist)||isNaN(mins)||dist<=0)return out('Enter distance and time.'); out('Pace: '+(mins/dist).toFixed(2)+' min/km');},
'paint-calculator.html':()=>{const area=n('feet'), cov=n('inches'); if(isNaN(area)||isNaN(cov)||cov<=0)return out('Enter area and coverage.'); out('Paint needed: '+(area/cov).toFixed(2)+' litres');},
'pay-raise-calculator.html':()=>{const salary=n('feet'), raise=n('inches'); if(isNaN(salary)||isNaN(raise))return out('Enter salary and raise.'); out('New salary: '+money(salary*(1+raise/100))+' • Increase: '+money(salary*raise/100));},
'paycheck-calculator.html':()=>{const salary=n('feet'), periods=n('inches'), tax=d(); if(isNaN(salary)||isNaN(periods)||periods<=0)return out('Enter salary and pay periods.'); const gross=salary/periods; out('Estimated pay per period: '+money(gross*(1-(isNaN(tax)?0:tax)/100)));},
'percent-change-calculator.html':()=>{const old=n('feet'), ne=n('inches'); if(isNaN(old)||isNaN(ne)||old===0)return out('Enter original and new values.'); out('Percent change: '+((ne-old)/old*100).toFixed(d())+'%');},
'percentage-calculator.html':()=>{const pctv=n('feet'), num=n('inches'); if(isNaN(pctv)||isNaN(num))return out('Enter percentage and number.'); out(pctv+'% of '+num+' = '+(pctv/100*num).toFixed(d()));},
'percentage-decrease-calculator.html':()=>{const original=n('feet'), dec=n('inches'); if(isNaN(original)||isNaN(dec))return out('Enter value and decrease.'); out('Result: '+(original*(1-dec/100)).toFixed(d()));},
'percentage-increase-calculator.html':()=>{const original=n('feet'), inc=n('inches'); if(isNaN(original)||isNaN(inc))return out('Enter value and increase.'); out('Result: '+(original*(1+inc/100)).toFixed(d()));},
'protein-intake-calculator.html':()=>{const w=n('feet'), target=n('inches'); if(isNaN(w)||isNaN(target))return out('Enter weight and protein target.'); out('Daily protein target: '+(w*target).toFixed(0)+' g');},
'quick-ratio-calculator.html':()=>{const assets=n('feet'), liabilities=n('inches'); if(isNaN(assets)||isNaN(liabilities)||liabilities<=0)return out('Enter quick assets and liabilities.'); out('Quick ratio: '+(assets/liabilities).toFixed(2)+':1');},
'ratio-calculator.html':()=>{let a=n('feet'), b=n('inches'); if(isNaN(a)||isNaN(b)||b===0)return out('Enter two numbers.'); function gcd(x,y){x=Math.abs(x);y=Math.abs(y);while(y){let t=y;y=x%y;x=t;}return x||1;} const g=gcd(a,b); out('Ratio: '+(a/g)+':'+(b/g));},
'refinance-savings-calculator.html':()=>{const current=n('feet'), ne=n('inches'), months=d(); if(isNaN(current)||isNaN(ne))return out('Enter current and new payments.'); out('Monthly savings: '+money(current-ne)+' • Savings over term: '+money((current-ne)*(isNaN(months)?0:months)));},
'retirement-savings-calculator.html':()=>{const p=n('feet'), rate=n('inches'), years=d(); if(isNaN(p)||isNaN(rate)||isNaN(years))return out('Enter savings, return, and years.'); out('Estimated retirement savings: '+money(p*Math.pow(1+rate/100,years)));},
'roi-calculator.html':()=>{const gain=n('feet'), cost=n('inches'); if(isNaN(gain)||isNaN(cost)||cost===0)return out('Enter gain and cost.'); out('ROI: '+((gain-cost)/cost*100).toFixed(d())+'%');},
'room-perimeter-calculator.html':()=>{const l=n('feet'), w=n('inches'); if(isNaN(l)||isNaN(w))return out('Enter length and width.'); out('Perimeter: '+(2*(l+w)).toFixed(2));},
'salary-calculator.html':()=>{const salary=n('feet'), hours=n('inches'), precision=d(); if(isNaN(salary)||isNaN(hours)||hours<=0)return out('Enter salary and hours.'); out('Hourly equivalent: '+money(salary/(hours*52)));},
'sales-tax-calculator.html':()=>{const price=n('feet'), tax=n('inches'); if(isNaN(price)||isNaN(tax))return out('Enter price and tax.'); out('Tax: '+money(price*tax/100)+' • Total: '+money(price*(1+tax/100)));},
'savings-calculator.html':()=>{const p=n('feet'), rate=n('inches'), years=d(); if(isNaN(p)||isNaN(rate)||isNaN(years))return out('Enter amount, rate, and term.'); out('Estimated savings: '+money(p*Math.pow(1+rate/100,years)));},
'savings-goal-calculator.html':()=>{const goal=n('feet'), current=n('inches'), monthly=d(); if(isNaN(goal)||isNaN(current)||isNaN(monthly)||monthly<=0)return out('Enter goal, current savings, and monthly contribution.'); out('Time to goal: '+monthsToText(Math.ceil((goal-current)/monthly)));},
'simple-interest-calculator.html':()=>{const p=n('feet'), rate=n('inches'), years=d(); if(isNaN(p)||isNaN(rate)||isNaN(years))return out('Enter principal, rate, and years.'); out('Simple interest: '+money(p*rate/100*years)+' • Total: '+money(p+(p*rate/100*years)));},
'slope-calculator.html':()=>{const p1=textVal('feet').split(',').map(Number), p2=textVal('inches').split(',').map(Number); if(p1.length<2||p2.length<2||p1.some(isNaN)||p2.some(isNaN)||p2[0]===p1[0])return out('Enter two points as x,y.'); out('Slope: '+((p2[1]-p1[1])/(p2[0]-p1[0])).toFixed(4));},
'midpoint-calculator.html':()=>{const p1=textVal('feet').split(',').map(Number), p2=textVal('inches').split(',').map(Number); if(p1.length<2||p2.length<2||p1.some(isNaN)||p2.some(isNaN))return out('Enter two points as x,y.'); out('Midpoint: ('+((p1[0]+p2[0])/2)+', '+((p1[1]+p2[1])/2)+')');},
'square-feet-to-square-metres-calculator.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter square feet.'); out(v+' sq ft = '+(v*0.092903).toFixed(2)+' m²');},
'square-metres-to-square-feet-calculator.html':()=>{const v=n('feet'); if(isNaN(v))return out('Enter square metres.'); out(v+' m² = '+(v*10.7639).toFixed(2)+' sq ft');},
'square-footage-calculator.html':()=>{const l=n('feet'), w=n('inches'); if(isNaN(l)||isNaN(w))return out('Enter length and width.'); out('Area: '+(l*w).toFixed(2)+' square feet');},
'standard-deviation-calculator.html':()=>{const v=numberList('feet'); if(v.length<2)return out('Enter at least two numbers.'); const mean=v.reduce((a,b)=>a+b,0)/v.length; const variance=v.reduce((a,b)=>a+Math.pow(b-mean,2),0)/v.length; out('Standard deviation: '+Math.sqrt(variance).toFixed(4));},
'tile-calculator.html':()=>{const area=n('feet'), length=n('inches'), width=d(); if(isNaN(area)||isNaN(length)||isNaN(width)||length<=0||width<=0)return out('Enter area and tile dimensions.'); const tileArea=(length/100)*(width/100); out('Tiles needed: '+Math.ceil(area/tileArea));},
'time-duration-calculator.html':()=>{const a=textVal('feet'), b=textVal('inches'); if(!a||!b)return out('Enter start and end times.'); const da=new Date('1970-01-01T'+a), db=new Date('1970-01-01T'+b); let diff=(db-da)/60000; if(diff<0)diff+=1440; out('Duration: '+Math.floor(diff/60)+' hours '+Math.round(diff%60)+' minutes');},
'tip-calculator.html':()=>{const bill=n('feet'), tip=n('inches'), people=d(); if(isNaN(bill)||isNaN(tip))return out('Enter bill and tip.'); const total=bill*(1+tip/100), split=people>0?people:1; out('Tip: '+money(bill*tip/100)+' • Total: '+money(total)+' • Per person: '+money(total/split));},
'vat-calculator.html':()=>{const amount=n('feet'), rate=n('inches'), direction=d(); if(isNaN(amount)||isNaN(rate))return out('Enter amount and VAT rate.'); if(direction===2)return out('VAT included: '+money(amount-amount/(1+rate/100))+' • Net: '+money(amount/(1+rate/100))); out('VAT: '+money(amount*rate/100)+' • Gross: '+money(amount*(1+rate/100)));},
'waist-to-hip-ratio-calculator.html':()=>{const waist=n('feet'), hip=n('inches'); if(isNaN(waist)||isNaN(hip)||hip<=0)return out('Enter waist and hip measurements.'); out('Waist-to-hip ratio: '+(waist/hip).toFixed(2));},
'water-intake-calculator.html':()=>{const weight=n('feet'), active=n('inches')||0; if(isNaN(weight))return out('Enter body weight.'); out('Estimated daily water: '+((weight*35)+(active*12)).toFixed(0)+' mL');},
'weeks-between-dates-calculator.html':()=>{const a=dt('feet'), b=dt('inches'); if(!a||!b||isNaN(a)||isNaN(b))return out('Choose both dates.'); out('Difference: '+(Math.abs(daysBetween(a,b))/7).toFixed(2)+' weeks');},
'weighted-average-calculator.html':()=>{const vals=numberList('feet'), weights=numberList('inches'); if(!vals.length||vals.length!==weights.length)return out('Enter matching values and weights.'); const sw=weights.reduce((a,b)=>a+b,0); out('Weighted average: '+(vals.reduce((a,v,i)=>a+v*weights[i],0)/sw).toFixed(4));}
,
'mortgage-affordability-calculator.html':()=>{const payment=n('feet'), rate=n('rate')/100/12, years=n('years'), deposit=n('deposit')||0; if(isNaN(payment)||isNaN(rate)||isNaN(years)||payment<=0||years<=0)return out('Enter monthly budget, rate, and term.'); const months=years*12; const loan=rate===0?payment*months:payment*(Math.pow(1+rate,months)-1)/(rate*Math.pow(1+rate,months)); out('Estimated affordable loan: '+money(loan)+' • Estimated home price with down payment: '+money(loan+deposit));},
'contractor-rate-calculator.html':()=>{const target=n('feet'), hours=n('inches'), overhead=(n('rate')||0)/100; if(isNaN(target)||isNaN(hours)||target<=0||hours<=0)return out('Enter target income and billable hours.'); const annualHours=hours*48; const hourly=target*(1+overhead)/annualHours; out('Estimated contractor rate: '+money(hourly)+'/hour • Annual billable hours: '+annualHours.toLocaleString());},
'leave-payout-calculator.html':()=>{const rate=n('feet'), hours=n('inches'), days=n('days'); if(isNaN(rate)||isNaN(hours)||isNaN(days)||rate<0||hours<0||days<0)return out('Enter pay rate, hours per day, and leave days.'); out('Estimated gross leave payout: '+money(rate*hours*days));},
'calorie-calculator.html':()=>{const kg=n('feet'), cm=n('inches'), age=n('age'), sex=n('sex'), activity=n('activity'); if([kg,cm,age,sex,activity].some(isNaN)||kg<=0||cm<=0||age<=0||activity<=0)return out('Enter weight, height, age, sex adjustment, and activity factor.'); const bmr=10*kg+6.25*cm-5*age+sex; out('Estimated maintenance calories: '+(bmr*activity).toFixed(0)+' kcal/day • BMR: '+bmr.toFixed(0)+' kcal/day');},
'bmr-calculator.html':()=>{const kg=n('feet'), cm=n('inches'), age=n('age'), sex=n('sex'); if([kg,cm,age,sex].some(isNaN)||kg<=0||cm<=0||age<=0)return out('Enter weight, height, age, and sex adjustment.'); const bmr=10*kg+6.25*cm-5*age+sex; out('Estimated BMR: '+bmr.toFixed(0)+' kcal/day');},
'roofing-calculator.html':()=>{const length=n('feet'), width=n('inches'), pitch=n('rate')||1, waste=(n('waste')||0)/100; if(isNaN(length)||isNaN(width)||length<=0||width<=0||pitch<=0)return out('Enter length, width, and pitch factor.'); const area=length*width*pitch*(1+waste); out('Estimated roof area with allowance: '+area.toFixed(d())+' square units');},
'fence-calculator.html':()=>{const length=n('feet'), panel=n('inches'), spacing=n('spacing')||panel; if(isNaN(length)||isNaN(panel)||isNaN(spacing)||length<=0||panel<=0||spacing<=0)return out('Enter fence length, panel width, and post spacing.'); out('Estimated panels: '+Math.ceil(length/panel)+' • Estimated posts: '+(Math.ceil(length/spacing)+1));},
'work-hours-calculator.html':()=>{const start=n('feet'), end=n('inches'), breaks=n('breaks')||0, days=n('days')||1; if(isNaN(start)||isNaN(end)||start<0||end<=start||breaks<0||days<=0)return out('Enter valid start time, end time, break, and days.'); const daily=end-start-breaks; if(daily<0)return out('Break time cannot exceed the shift length.'); out('Total work hours: '+(daily*days).toFixed(d())+' hours • Daily paid hours: '+daily.toFixed(d()));}

});

function resetCalculator(){document.querySelectorAll('input').forEach(i=>i.value=''); if(decimalsSelect) decimalsSelect.value='2'; out('Enter values to begin'); if(feetInput) feetInput.focus();}

Object.assign(calculatorConfigs,{
'body-fat-calculator.html':()=>{const waist=n('inches'), neck=n('rate'), height=n('years'); const sexEl=$('sex'); const sex=sexEl?sexEl.value:'male'; if([waist,neck,height].some(isNaN)||waist<=0||neck<=0||height<=0)return out('Enter waist, neck and height measurements.'); let bf; if(sex==='female'){const hip=n('feet'); bf=495/(1.29579-0.35004*Math.log10(Math.max(1,waist+hip-neck))+0.22100*Math.log10(height))-450;} else {bf=495/(1.0324-0.19077*Math.log10(Math.max(1,waist-neck))+0.15456*Math.log10(height))-450;} if(!isFinite(bf))return out('Check the measurements and try again.'); out('Estimated body fat: '+bf.toFixed(1)+'%');},
'tdee-calculator.html':()=>{const kg=n('feet'), cm=n('inches'), age=n('age'), sex=n('sex'), activity=n('activity'); if([kg,cm,age,sex,activity].some(isNaN)||kg<=0||cm<=0||age<=0)return out('Enter weight, height, age, sex and activity level.'); const bmr=10*kg+6.25*cm-5*age+sex; out('Estimated TDEE: '+(bmr*activity).toFixed(0)+' kcal/day • BMR: '+bmr.toFixed(0)+' kcal/day');},
'macro-calculator.html':()=>{const calories=n('feet'), protein=n('inches'), fat=n('rate'); if([calories,protein,fat].some(isNaN)||calories<=0||protein<0||fat<0)return out('Enter calories, protein and fat.'); const remaining=calories-(protein*4)-(fat*9); if(remaining<0)return out('Protein and fat exceed the calorie target.'); out('Protein: '+protein.toFixed(0)+' g • Fat: '+fat.toFixed(0)+' g • Carbs: '+(remaining/4).toFixed(0)+' g');},
'drywall-calculator.html':()=>{const area=n('feet'), sheet=n('inches'), waste=n('rate')||0; if([area,sheet].some(isNaN)||area<=0||sheet<=0)return out('Enter wall area and sheet area.'); out('Estimated sheets needed: '+Math.ceil(area*(1+waste/100)/sheet).toLocaleString());},
'wallpaper-calculator.html':()=>{const area=n('feet'), roll=n('inches'), waste=n('rate')||0; if([area,roll].some(isNaN)||area<=0||roll<=0)return out('Enter wall area and roll coverage.'); out('Estimated rolls needed: '+Math.ceil(area*(1+waste/100)/roll).toLocaleString());},
'decking-calculator.html':()=>{const area=n('feet'), board=n('inches'), waste=n('rate')||0; if([area,board].some(isNaN)||area<=0||board<=0)return out('Enter deck area and board coverage.'); out('Estimated boards needed: '+Math.ceil(area*(1+waste/100)/board).toLocaleString());},
'time-card-calculator.html':()=>{const start=n('feet'), end=n('inches'), breakMin=n('rate')||0, days=n('years')||1; if([start,end,days].some(isNaN)||end<start||days<=0)return out('Enter start time, end time and days.'); const hours=(end-start)-(breakMin/60); out('Paid hours: '+(hours*days).toFixed(2)+' hours');},
'week-number-calculator.html':()=>{const date=dt('feet'); if(!date||isNaN(date))return out('Choose a date.'); const dte=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())); const day=dte.getUTCDay()||7; dte.setUTCDate(dte.getUTCDate()+4-day); const yearStart=new Date(Date.UTC(dte.getUTCFullYear(),0,1)); const week=Math.ceil((((dte-yearStart)/86400000)+1)/7); out('ISO week: '+week+' • ISO week-year: '+dte.getUTCFullYear());}
});

if(calculateBtn&&resetBtn){const keyBase=calculatorKey.replace(/\.html$/,''); const pageBase=currentPage.replace(/\.html$/,''); const candidates=[currentPage, calculatorKey, calculatorKey+'.html', keyBase, keyBase+'.html', pageBase, pageBase+'.html', currentPage.replace('-calculator.html','.html'), pageBase.replace('-calculator','')+'.html']; const fn=candidates.map(k=>calculatorConfigs[k]).find(Boolean); if(fn){calculateBtn.addEventListener('click',fn); resetBtn.addEventListener('click',resetCalculator); document.querySelectorAll('input').forEach(i=>i.addEventListener('keydown',e=>{if(e.key==='Enter')fn();}));}}
const mainCalcScreen=$('mainCalcScreen'); const mainCalcKeys=document.querySelectorAll('.calc-key'); if(mainCalcScreen&&mainCalcKeys.length){let expr=''; const display=()=>mainCalcScreen.textContent=(expr||'0').replace(/\*/g,'×').replace(/\//g,'÷').replace(/-/g,'−'); mainCalcKeys.forEach(btn=>btn.addEventListener('click',()=>{const v=btn.dataset.value,a=btn.dataset.action; if(a==='clear'){expr='';display();return;} if(a==='backspace'){expr=expr.slice(0,-1);display();return;} if(a==='equals'){try{const r=Function('"use strict";return ('+expr.replace(/%/g,'/100')+')')(); expr=isFinite(r)?Number(r.toFixed(10)).toString():''; mainCalcScreen.textContent=expr||'Error';}catch{expr='';mainCalcScreen.textContent='Error';} return;} if(v){expr+=v;display();}}));}
